# Generated by Django 6.1 on 2026-08-28 21:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
